### ISSUE TITLE
specify date

### ISSUE THREAD

**Issue by MangoIV** [sibbl/sachsen-impfnotifier#14]
Hi. it would be great if there was an option to specify the date from which the appointment shall be searched. That would be helpful for people who are only rightfully able to book an appointment from June 7th.

**Comment by sibbl** [comment]
Thanks for your feedback! I would appreciate a contribution with such a feature, although I only see this as very low priority.

As far as I know it's still not possible to register legally as someone of priority group 4 and I highly doubt there will be many new appointments within the next 3 days anyway.

**Comment by MangoIV** [comment]
I don't do javascript so I might have my troubles reading into it so the contribution will probably not come from me, I'm sorry. I agree however, that it might not be top priority and if nobody implements it soon the problem is voided anyway as from the 7th everybody would be able to register... Thanks for your considerations, tho :)
